@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":InternBookParser" as InternBookParser LOGIC_COLOR
participant ":FindCommandParser" as FindCommandParser LOGIC_COLOR
participant "d:FindCommand" as FindCommand LOGIC_COLOR
participant "r:CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant "m:Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("find ABC")
activate LogicManager

LogicManager -> InternBookParser : parseCommand("find ABC")
activate InternBookParser

create FindCommandParser
InternBookParser -> FindCommandParser
activate FindCommandParser

FindCommandParser --> InternBookParser
deactivate FindCommandParser

InternBookParser -> FindCommandParser : parse("ABC")
activate FindCommandParser

create FindCommand
FindCommandParser -> FindCommand
activate FindCommand

FindCommand --> FindCommandParser :
deactivate FindCommand

FindCommandParser --> InternBookParser : d
deactivate FindCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
FindCommandParser -[hidden]-> InternBookParser
destroy FindCommandParser

InternBookParser --> LogicManager : d
deactivate InternBookParser

LogicManager -> FindCommand : execute(m)
activate FindCommand

FindCommand -> Model : updateFilteredCompanyList(predicate)
activate Model

Model --> FindCommand
deactivate Model

create CommandResult
FindCommand -> CommandResult
activate CommandResult

CommandResult --> FindCommand
deactivate CommandResult

FindCommand --> LogicManager : r
deactivate FindCommand

[<--LogicManager
deactivate LogicManager
@enduml
