@startuml
!include style.puml
skinparam ClassFontColor #000000
skinparam ClassBorderColor #000000
skinparam ClassBackgroundColor #FFFFAA

title After command "list"

package States <<rectangle>> {
    class State1 as "<u>ib0:InternBook</u>"
    class State2 as "<u>ib1:InternBook</u>"
    class State3 as "<u>ib2:InternBook</u>"
}

State1 -[hidden]right-> State2
State2 -[hidden]right-> State3

class Pointer as "Current State" #FFFFFF

Pointer -up-> State2
@end
