@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant ":VersionedInternBook" as VersionedInternBook MODEL_COLOR
end box

[-> Model : undoInternBook()
activate Model

Model -> VersionedInternBook : undo()
activate VersionedInternBook

VersionedInternBook -> VersionedInternBook :resetData(ReadOnlyInternBook)
VersionedInternBook --> Model :
deactivate VersionedInternBook

[<-- Model
deactivate Model

@enduml
