@startuml
!include ../style.puml
skinparam ArrowFontStyle plain

Participant ":LogicManager" as logic LOGIC_COLOR
Participant ":InternBookParser" as inp LOGIC_COLOR
Participant ":EditCommandParser" as ecp LOGIC_COLOR
Participant "command:EditCommand" as ec LOGIC_COLOR

[-> logic : execute
activate logic
logic -> inp ++: parseCommand(commandText)
create ecp
inp -> ecp
inp -> ecp ++: parse(arguments)
create ec
ecp -> ec ++: index, editCompanyDescriptor
ec --> ecp --
ecp --> inp --: command
inp --> logic --: command

@enduml
